// The verification date is when PINGOO checked the cited publisher/developer/store pages.
// Avoid storing volatile prices, review metrics, or claims not represented by those sources.
const checked = '2026-10-09'
const source = (name, url, kind = 'official-site') => ({ name, url, kind, verifiedAt: checked })

export const verifiedGames = [
  {
    id: 'dota-2', catalogStatus: 'verified', slug: 'dota-2', title: 'Dota 2',
    tagline: 'A free-to-play multiplayer online battle arena game from Valve.',
    description: 'Dota 2 is a multiplayer online battle arena game developed and published by Valve. Its official Steam listing describes a game played by two teams of five, with a large roster of heroes and matches built around destroying the opposing team’s Ancient.',
    genres: ['moba', 'strategy'], platforms: ['pc'], developer: 'Valve', publisher: 'Valve', releaseYear: 2013,
    image: undefined, features: ['Five-player teams', 'More than 100 heroes'],
    requirements: { minimum: ['OS: Windows 7 or newer', 'CPU: Dual-core 2.8 GHz', 'Memory: 4 GB RAM', 'Graphics: NVIDIA 8600/9600GT, ATI/AMD Radeon HD 2600/3600', 'DirectX: Version 11', 'Storage: 60 GB available'], recommended: [] },
    sources: [source('Dota 2 on Steam', 'https://store.steampowered.com/app/570/Dota_2/', 'product-store')], lastVerifiedAt: checked,
    provenance: { title: ['https://store.steampowered.com/app/570/Dota_2/'], summary: ['https://store.steampowered.com/app/570/Dota_2/'], description: ['https://store.steampowered.com/app/570/Dota_2/'], developer: ['https://store.steampowered.com/app/570/Dota_2/'], publisher: ['https://store.steampowered.com/app/570/Dota_2/'], releaseYear: ['https://store.steampowered.com/app/570/Dota_2/'], platforms: ['https://store.steampowered.com/app/570/Dota_2/'], genres: ['https://store.steampowered.com/app/570/Dota_2/'], features: ['https://store.steampowered.com/app/570/Dota_2/'], requirements: ['https://store.steampowered.com/app/570/Dota_2/'] },
  },
  {
    id: 'pubg-battlegrounds', catalogStatus: 'verified', slug: 'pubg-battlegrounds', title: 'PUBG: BATTLEGROUNDS',
    tagline: 'A battle royale shooter published by KRAFTON.',
    description: 'PUBG: BATTLEGROUNDS is a battle royale game. Its Steam product listing identifies PUBG Studios as developer and KRAFTON, Inc. as publisher, and provides the current Windows system requirements.',
    genres: ['battle-royale', 'shooter', 'action'], platforms: ['pc'], developer: 'PUBG Studios', publisher: 'KRAFTON, Inc.', releaseYear: 2017,
    features: ['Battle royale matches', 'Online multiplayer'],
    requirements: { minimum: ['OS: 64-bit Windows 10', 'CPU: Intel Core i5-4430 or AMD FX-6300', 'Memory: 8 GB RAM', 'Graphics: NVIDIA GeForce GTX 960 2 GB or AMD Radeon R7 370 2 GB', 'DirectX: Version 11', 'Storage: 40 GB available'], recommended: ['OS: 64-bit Windows 10', 'CPU: Intel Core i5-6600K or AMD Ryzen 5 1600', 'Memory: 16 GB RAM', 'Graphics: NVIDIA GeForce GTX 1060 3 GB or AMD Radeon RX 580 4 GB', 'DirectX: Version 11', 'Storage: 50 GB available'] },
    sources: [source('PUBG: BATTLEGROUNDS on Steam', 'https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/', 'product-store')], lastVerifiedAt: checked,
    provenance: { title: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'], summary: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'], description: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'], developer: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'], publisher: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'], releaseYear: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'], platforms: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'], genres: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'], features: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'], requirements: ['https://store.steampowered.com/app/578080/PUBG_BATTLEGROUNDS/'] },
  },
  {
    id: 'minecraft', catalogStatus: 'verified', slug: 'minecraft', title: 'Minecraft',
    tagline: 'A sandbox game available in Java and Bedrock editions.',
    description: 'Minecraft is a sandbox game. Mojang’s official PC store page offers Java and Bedrock editions together; Java Edition is listed for Windows, macOS and Linux, while Bedrock Edition is available across PC, consoles and mobile devices, subject to edition and device requirements.',
    genres: ['sandbox', 'survival', 'open-world', 'adventure'], platforms: ['pc', 'playstation', 'xbox', 'switch', 'android', 'ios'], developer: 'Mojang Studios', publisher: 'Mojang Studios', releaseYear: 2011,
    features: ['Java and Bedrock editions are available for PC', 'Java and Bedrock have different cross-play compatibility'],
    sources: [source('Minecraft official game information', 'https://www.minecraft.net/en-us/about-minecraft'), source('Minecraft: Java & Bedrock Edition for PC', 'https://www.minecraft.net/en-us/store/minecraft-java-bedrock-edition-pc'), source('Minecraft Java Edition system requirements', 'https://www.minecraft.net/en-us/article/minecraft-java-edition-system-requirements')], lastVerifiedAt: checked,
    provenance: { title: ['https://www.minecraft.net/en-us/about-minecraft'], summary: ['https://www.minecraft.net/en-us/about-minecraft'], description: ['https://www.minecraft.net/en-us/about-minecraft'], developer: ['https://www.minecraft.net/en-us/store/minecraft-java-bedrock-edition-pc'], publisher: ['https://www.minecraft.net/en-us/store/minecraft-java-bedrock-edition-pc'], releaseYear: ['https://www.minecraft.net/en-us/about-minecraft'], platforms: ['https://www.minecraft.net/en-us/about-minecraft'], genres: ['https://www.minecraft.net/en-us/about-minecraft'], features: ['https://www.minecraft.net/en-us/about-minecraft'] },
  },
  {
    id: 'genshin-impact', catalogStatus: 'verified', slug: 'genshin-impact', title: 'Genshin Impact',
    tagline: 'An action role-playing game from HoYoverse.',
    description: 'Genshin Impact is an action role-playing game. HoYoverse’s platform notices document availability on PC, iOS, Android, PlayStation and Xbox Series X|S. PlayStation 4 support has ended; this page does not list it as a currently supported platform.',
    genres: ['action-rpg', 'open-world', 'action', 'rpg', 'adventure'], platforms: ['pc', 'playstation', 'xbox', 'android', 'ios'], developer: 'HoYoverse', publisher: 'HoYoverse', releaseYear: 2020,
    features: ['Open-world exploration', 'Action combat'],
    sources: [source('Genshin Impact official site', 'https://genshin.hoyoverse.com/en/'), source('Genshin Impact platform update notice', 'https://genshin.hoyoverse.com/en/news/detail/163454'), source('Genshin Impact launch and device information', 'https://genshin.hoyoverse.com/en/news/detail/5284'), source('Genshin Impact on PlayStation Store', 'https://store.playstation.com/en-us/product/UP6262-PPSA02562_00-OSRELSIEAGENSHIN/', 'product-store')], lastVerifiedAt: checked,
    provenance: { title: ['https://genshin.hoyoverse.com/en/'], summary: ['https://genshin.hoyoverse.com/en/'], description: ['https://genshin.hoyoverse.com/en/'], developer: ['https://genshin.hoyoverse.com/en/'], publisher: ['https://genshin.hoyoverse.com/en/'], releaseYear: ['https://genshin.hoyoverse.com/en/news/detail/5284'], platforms: ['https://genshin.hoyoverse.com/en/news/detail/163454'], genres: ['https://store.playstation.com/en-us/product/UP6262-PPSA02562_00-OSRELSIEAGENSHIN/'], features: ['https://genshin.hoyoverse.com/en/news/detail/5284'] },
  },
  {
    id: 'valorant', catalogStatus: 'verified', slug: 'valorant', title: 'VALORANT',
    tagline: 'A competitive tactical shooter developed and published by Riot Games.',
    description: 'VALORANT is a tactical shooter developed and published by Riot Games. This profile documents PC availability and Riot’s Windows hardware specifications. Riot also documents console versions, but their availability varies by region; console platforms are not generalized here.',
    genres: ['tactical-shooter', 'shooter'], platforms: ['pc'], developer: 'Riot Games', publisher: 'Riot Games', releaseYear: 2020,
    features: ['Competitive tactical team shooter'],
    requirements: { minimum: ['OS: Windows 10 (Build 19041+) 64-bit or Windows 11 64-bit', 'CPU: Intel Core 2 Duo E8400 or AMD Athlon 200GE', 'Memory: 4 GB RAM', 'Graphics: Intel HD 4000 or AMD Radeon R5 220'], recommended: ['OS: Windows 10 (Build 19041+) 64-bit or Windows 11 64-bit', 'CPU: Intel Core i3-4150 or AMD Ryzen 3 1200', 'Memory: 4 GB RAM', 'Graphics: NVIDIA GeForce GT 730 or AMD Radeon R7 240'] },
    sources: [source('VALORANT', 'https://playvalorant.com/'), source('VALORANT PC specifications', 'https://playvalorant.com/en-us/specs/'), source('VALORANT launch announcement', 'https://playvalorant.com/en-us/news/announcements/valorant-closed-beta-ends-may-28/'), source('VALORANT console regional availability', 'https://playvalorant.com/en-us/news/announcements/valorant-coming-to-console-in-australia--new-zealand/')], lastVerifiedAt: checked,
    provenance: { title: ['https://playvalorant.com/'], summary: ['https://playvalorant.com/'], description: ['https://playvalorant.com/en-us/specs/'], developer: ['https://playvalorant.com/'], publisher: ['https://playvalorant.com/'], releaseYear: ['https://playvalorant.com/en-us/news/announcements/valorant-closed-beta-ends-may-28/'], platforms: ['https://playvalorant.com/en-us/specs/'], genres: ['https://playvalorant.com/'], features: ['https://playvalorant.com/'], requirements: ['https://playvalorant.com/en-us/specs/'] },
  },
  {
    id: 'arc-raiders', catalogStatus: 'verified', slug: 'arc-raiders', title: 'ARC Raiders',
    tagline: 'A multiplayer extraction adventure from Embark Studios.',
    description: 'ARC Raiders is a multiplayer extraction adventure developed and published by Embark Studios. The official site lists PC, PlayStation 5 and Xbox Series X|S, and describes cross-platform social play. Steam lists the PC system requirements.',
    genres: ['action-adventure', 'shooter', 'action', 'adventure'], platforms: ['pc', 'playstation', 'xbox'], developer: 'Embark Studios', publisher: 'Embark Studios', releaseYear: 2025,
    features: ['Multiplayer extraction adventure', 'Cross-platform social play'],
    requirements: { minimum: ['OS: Windows 10 64-bit', 'CPU: Intel Core i5-6600K or AMD Ryzen 5 1600', 'Memory: 12 GB RAM', 'Graphics: NVIDIA GeForce GTX 1050 Ti, AMD Radeon RX 580, or Intel Arc A380', 'DirectX: Version 12'], recommended: ['OS: Windows 10 64-bit', 'CPU: Intel Core i5-9600K or AMD Ryzen 5 3600', 'Memory: 16 GB RAM', 'Graphics: NVIDIA GeForce RTX 2070, AMD Radeon RX 5700 XT, or Intel Arc B570', 'DirectX: Version 12'] },
    sources: [source('ARC Raiders', 'https://arcraiders.com/en'), source('ARC Raiders on Steam', 'https://store.steampowered.com/app/1808500/ARC_Raiders/', 'product-store')], lastVerifiedAt: checked,
    provenance: { title: ['https://arcraiders.com/en'], summary: ['https://arcraiders.com/en'], description: ['https://arcraiders.com/en'], developer: ['https://store.steampowered.com/app/1808500/ARC_Raiders/'], publisher: ['https://store.steampowered.com/app/1808500/ARC_Raiders/'], releaseYear: ['https://arcraiders.com/en'], platforms: ['https://arcraiders.com/en'], genres: ['https://arcraiders.com/en'], features: ['https://arcraiders.com/en'], requirements: ['https://store.steampowered.com/app/1808500/ARC_Raiders/'] },
  },
  {
    id: 'resident-evil-requiem', catalogStatus: 'verified', slug: 'resident-evil-requiem', title: 'Resident Evil Requiem',
    tagline: 'A survival horror game developed and published by Capcom.',
    description: 'Resident Evil Requiem is a survival horror game developed and published by Capcom. The official PlayStation listing and Steam product page identify the game and its PC and PlayStation 5 versions; Steam publishes the PC requirements.',
    genres: ['survival-horror', 'horror', 'action'], platforms: ['pc', 'playstation'], developer: 'Capcom', publisher: 'Capcom', releaseYear: 2026,
    features: ['Single-player campaign'],
    requirements: { minimum: ['OS: Windows 11 64-bit', 'CPU: Intel Core i5-8500 or AMD Ryzen 5 3500', 'Memory: 16 GB RAM', 'Graphics: NVIDIA GeForce GTX 1660 6 GB or AMD Radeon RX 5500 XT 8 GB', 'DirectX: Version 12', 'Storage: SSD required'], recommended: ['OS: Windows 11 64-bit', 'CPU: Intel Core i7-8700 or AMD Ryzen 5 5500', 'Memory: 16 GB RAM', 'Graphics: NVIDIA GeForce RTX 2060 Super 8 GB or AMD Radeon RX 6600 8 GB', 'DirectX: Version 12', 'Storage: SSD required'] },
    sources: [source('Resident Evil Requiem on Steam', 'https://store.steampowered.com/app/3764200/Resident_Evil_Requiem/', 'product-store'), source('Resident Evil Requiem on PlayStation Store', 'https://store.playstation.com/en-us/product/UP0102-PPSA30803_00-REREQUIEM0000000', 'product-store')], lastVerifiedAt: checked,
    provenance: { title: ['https://store.steampowered.com/app/3764200/Resident_Evil_Requiem/'], summary: ['https://store.playstation.com/en-us/product/UP0102-PPSA30803_00-REREQUIEM0000000'], description: ['https://store.playstation.com/en-us/product/UP0102-PPSA30803_00-REREQUIEM0000000'], developer: ['https://store.steampowered.com/app/3764200/Resident_Evil_Requiem/'], publisher: ['https://store.steampowered.com/app/3764200/Resident_Evil_Requiem/'], releaseYear: ['https://store.playstation.com/en-us/product/UP0102-PPSA30803_00-REREQUIEM0000000'], platforms: ['https://store.steampowered.com/app/3764200/Resident_Evil_Requiem/'], genres: ['https://store.playstation.com/en-us/product/UP0102-PPSA30803_00-REREQUIEM0000000'], features: ['https://store.playstation.com/en-us/product/UP0102-PPSA30803_00-REREQUIEM0000000'], requirements: ['https://store.steampowered.com/app/3764200/Resident_Evil_Requiem/'] },
  },
  {
    id: 'crimson-desert', catalogStatus: 'verified', slug: 'crimson-desert', title: 'Crimson Desert',
    tagline: 'An open-world action-adventure developed and published by Pearl Abyss.',
    description: 'Crimson Desert is an open-world action-adventure game developed and published by Pearl Abyss. The publisher lists PC, PlayStation 5, Xbox Series X|S and Mac availability. No PC requirements are shown here because an official requirements specification was not confirmed in this review.',
    genres: ['action-adventure', 'open-world', 'action', 'adventure'], platforms: ['pc', 'playstation', 'xbox'], developer: 'Pearl Abyss', publisher: 'Pearl Abyss', releaseYear: 2026,
    features: ['Open-world action-adventure'],
    sources: [source('Crimson Desert', 'https://crimsondesert.pearlabyss.com/en-US/Main/index'), source('Pearl Abyss release and platform notice', 'https://www.pearlabyss.com/en-US/Board/Detail?_boardNo=14684')], lastVerifiedAt: checked,
    provenance: { title: ['https://crimsondesert.pearlabyss.com/en-US/Main/index'], summary: ['https://www.pearlabyss.com/en-US/Board/Detail?_boardNo=14684'], description: ['https://www.pearlabyss.com/en-US/Board/Detail?_boardNo=14684'], developer: ['https://www.pearlabyss.com/en-US/Board/Detail?_boardNo=14684'], publisher: ['https://www.pearlabyss.com/en-US/Board/Detail?_boardNo=14684'], releaseYear: ['https://www.pearlabyss.com/en-US/Board/Detail?_boardNo=14684'], platforms: ['https://www.pearlabyss.com/en-US/Board/Detail?_boardNo=14684'], genres: ['https://www.pearlabyss.com/en-US/Board/Detail?_boardNo=14684'], features: ['https://www.pearlabyss.com/en-US/Board/Detail?_boardNo=14684'] },
  },
  {
    id: 'forza-horizon-6', catalogStatus: 'verified', slug: 'forza-horizon-6', title: 'Forza Horizon 6',
    tagline: 'An open-world racing game from Playground Games and Xbox Game Studios.',
    description: 'Forza Horizon 6 is an open-world racing game developed by Playground Games and published by Xbox Game Studios. The official game page lists Xbox Series X|S and PC as available; its October 2026 notice lists PlayStation 5 for a future January 2027 release. Steam publishes the PC system requirements.',
    genres: ['racing', 'open-world'], platforms: ['pc', 'xbox'], developer: 'Playground Games', publisher: 'Xbox Game Studios', releaseYear: 2026,
    features: ['Open-world driving', 'PC and Xbox Series X|S availability'],
    requirements: { minimum: ['OS: Windows 10 22H2 (version 19045) or higher', 'CPU: Intel Core i5-8400 or AMD Ryzen 5 1600', 'Memory: 16 GB RAM', 'Graphics: NVIDIA GTX 1650, AMD RX 6500 XT, or Intel Arc A380', 'DirectX: Version 12', 'Storage: 167 GB; SSD required'], recommended: ['OS: Windows 10 22H2 (version 19045) or higher', 'CPU: Intel Core i5-12400F or AMD Ryzen 5 5600X', 'Memory: 16 GB RAM', 'Graphics: NVIDIA RTX 3060 Ti, AMD RX 6700 XT, or Intel Arc A580', 'DirectX: Version 12', 'Storage: 167 GB; SSD required'] },
    sources: [source('Forza Horizon 6', 'https://forza.net/forzahorizon6'), source('Forza Horizon 6 on Steam', 'https://store.steampowered.com/app/2483190/Forza_Horizon_6/', 'product-store'), source('Forza Horizon 6 PS5 release notice', 'https://forza.net/news/forza-horizon-6-pre-order-ps5')], lastVerifiedAt: checked,
    provenance: { title: ['https://forza.net/forzahorizon6'], summary: ['https://forza.net/forzahorizon6'], description: ['https://forza.net/forzahorizon6'], developer: ['https://store.steampowered.com/app/2483190/Forza_Horizon_6/'], publisher: ['https://store.steampowered.com/app/2483190/Forza_Horizon_6/'], releaseYear: ['https://forza.net/forzahorizon6'], platforms: ['https://forza.net/forzahorizon6'], genres: ['https://forza.net/forzahorizon6'], features: ['https://forza.net/forzahorizon6'], requirements: ['https://store.steampowered.com/app/2483190/Forza_Horizon_6/'] },
  },
]
